apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5432
  selector:
    {{- include "timescaledb.selectorLabels" . | nindent 4 }}
  type: ClusterIP