apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{ include "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "timescaledb.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "timescaledb.fullname" . }}   
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "timescaledb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.databaseName }}
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: root-password
              name: {{ .Release.Name }}-timescaledb-secret
        ports:
        - containerPort: 5432
          name: timescaledb
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: "{{ .Release.Name }}-timescaledb-pvc"
          mountPath: /home/postgres/pgdata/data
  volumeClaimTemplates:
  - metadata:
      name: "{{ .Release.Name }}-timescaledb-pvc"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persisted.storage }}    