apiVersion: v1
kind: Service
metadata:
  name: {{ include "cWarmerApp.fullname" . }}
  labels:
    {{- include "cWarmerApp.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3000
  selector:
    {{- include "cWarmerApp.selectorLabels" . | nindent 4 }}
  type: ClusterIP