apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-web-conf"
data:
  default.conf: |
    real_ip_header X-Forwarded-For;
    set_real_ip_from 10.0.0.0/8;
    set_real_ip_from 172.0.0.0/8;
    real_ip_recursive on;
    server {
        listen 80;
        server_name cwarmer.codilar.dev;
        location / {
        proxy_pass http://app-cwarmerapp:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        }
    }