apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-mysql-secret"
type: Opaque
data:
  root-password: {{ .Values.root_password | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
