apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "botservice.fullname" . }}
  labels:
    {{- include "botservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "botservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "botservice.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "botservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: RABBITMQ_HOST
            value: {{ .Values.rabbitmqHost | quote }}
          - name: RABBITMQ_PORT
            value: {{ .Values.rabbitmqPort | quote }}
          - name: RABBITMQ_USERNAME
            value: {{ .Values.rabbitmqUserName | quote }}
          - name: RABBITMQ_PASSWORD
            value: {{ .Values.rabbitmqPassword | quote }}
          - name: NUMBER_OF_THREADS
            value: {{ .Values.numberOfThreads | quote }}
          - name: MAX_NUMBER_OF_THREADS
            value: {{ .Values.maxNumberOfThreads | quote }}
          - name: TABLE_NAME
            value: {{ .Values.tableName | quote }}
          - name: CWARMER_USER_LOG_API_URL
            value: {{ .Values.cwarmerUserLogApiUrl | quote }}
          - name: TOKEN
            value: {{ .Values.token | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
